services:
  node-cli:
    build:
      context: ./../.
      dockerfile: ./.docker/app/Dockerfile.dev
      target: node-cli
      ssh:
        - default
    volumes:
      - ./../:/app
      - ~/.gitconfig:/root/.gitconfig 
    working_dir: /app
    networks:
      - ${NETWORKS}
    env_file:
      - ./.env
  node-server-debug:
    build:
      context: ./../.
      dockerfile: ./.docker/app/Dockerfile.dev
      target: node-server-debug
      ssh:
        - default
    volumes:
      - ./../:/app
    working_dir: /app
    networks:
      - ${NETWORKS}
    env_file:
      - ./.env
    ports:
      - 3000:3000
      - 9229:9229
    command: sh -c "npm install && npm run build && NODE_ENV=development npm run start:debug"
networks:
  zerveros:
    driver: bridge
